-- 1 the total number of films in each category
SELECT c.name AS category_name, COUNT(f.film_id) AS total_films
FROM category c
LEFT JOIN film_category fc 
ON c.category_id = fc.category_id
LEFT JOIN film f 
ON fc.film_id = f.film_id
GROUP BY c.name;
-- 2 the names of actors who have acted in more than 10 films
SELECT a.first_name, a.last_name, COUNT(fa.film_id) AS total_films
FROM actor a
JOIN film_actor fa 
ON a.actor_id = fa.actor_id
GROUP BY a.actor_id
HAVING total_films > 10;
-- 3 the average rental duration of films categorized as 'Action'.
SELECT AVG(f.rental_duration) AS average_rental_duration
FROM film f
JOIN film_category fc 
ON f.film_id = fc.film_id
JOIN category c 
ON fc.category_id = c.category_id
WHERE c.name = 'Action';
-- 4 the customers and their total_rentals
SELECT c.first_name, c.last_name, COUNT(r.rental_id) AS total_rentals
FROM customer c
JOIN rental r 
ON c.customer_id = r.customer_id
GROUP BY c.customer_id
ORDER BY total_rentals DESC
LIMIT 10;
-- 5 the total amount from rentals 
SELECT SUM(p.amount) AS total_amount_from_rentals
FROM payment P;
-- 6 the customers names based on their total spending on rentals
SELECT c.first_name, c.last_name, SUM(p.amount) AS total_spent
FROM customer c
JOIN payment p 
ON c.customer_id = p.customer_id
GROUP BY c.customer_id
ORDER BY total_spent DESC;
-- 7 the staff members and the number of rentals they processed
SELECT s.first_name, s.last_name, COUNT(r.rental_id) AS rentals_processed
FROM staff s
LEFT JOIN rental r 
ON s.staff_id = r.staff_id
GROUP BY s.staff_id;
-- 8 all films and there length
SELECT title, length
FROM film
ORDER BY length DESC;
-- 9 the actors who have appeared in films BASED ON rental rate.
SELECT distinct (a.first_name), f.rental_rate
FROM actor a
JOIN film_actor fa 
ON a.actor_id = fa.actor_id
JOIN film f 
ON fa.film_id = f.film_id
ORDER BY f.rental_rate DESC;
-- 10 the total count of customers in each country
SELECT co.country, COUNT(c.customer_id) AS total_customers
FROM country co
JOIN city ci 
ON co.country_id = ci.country_id
JOIN address a 
ON ci.city_id = a.city_id
JOIN customer c 
ON a.address_id = c.address_id
GROUP BY co.country
ORDER BY total_customers DESC ;
-- 11 the films that have been rented more than five time
SELECT f.title, COUNT(r.rental_id) AS rental_count
FROM film f
JOIN inventory i 
ON f.film_id = i.film_id
JOIN rental r 
ON i.inventory_id = r.inventory_id
GROUP BY f.film_id
HAVING rental_count > 5
ORDER BY rental_count DESC;
-- 12 the total number of rentals and total amount by each film
SELECT f.title, COUNT(r.rental_id) AS total_rentals, SUM(p.amount) AS total_amount
FROM film f
LEFT JOIN inventory i 
ON f.film_id = i.film_id
LEFT JOIN rental r 
ON i.inventory_id = r.inventory_id
LEFT JOIN payment p 
ON r.rental_id = p.rental_id
GROUP BY f.film_id
ORDER BY total_rentals DESC;
-- 13 the total amount generated by each category of films
SELECT c.name AS category, SUM(p.amount) AS total_amount
FROM category c
JOIN film_category fc 
ON c.category_id = fc.category_id
JOIN film f 
ON fc.film_id = f.film_id
JOIN inventory i 
ON f.film_id = i.film_id
JOIN rental r 
ON i.inventory_id = r.inventory_id
JOIN payment p 
ON r.rental_id = p.rental_id
GROUP BY c.category_id;
-- 14 the total number of films rented by each customer
SELECT c.first_name, c.last_name, COUNT(f.film_id) AS total_films
FROM customer c
LEFT JOIN rental r ON c.customer_id = r.customer_id
LEFT JOIN inventory i ON r.inventory_id = i.inventory_id
LEFT JOIN film f ON i.film_id = f.film_id
GROUP BY c.customer_id
ORDER BY total_films DESC;
-- 15 the average rental rate for films in each category
SELECT c.name AS category_name, AVG(f.rental_rate) AS average_rental_rate
FROM category c
JOIN film_category fc 
ON c.category_id = fc.category_id
JOIN film f 
ON fc.film_id = f.film_id
GROUP BY c.category_id
ORDER BY average_rental_rate DESC;
-- 16 the number of actors in each film
SELECT f.title, COUNT(fa.actor_id) AS total_actors
FROM film f
LEFT JOIN film_actor fa 
ON f.film_id = fa.film_id
GROUP BY f.film_id
ORDER BY total_actors DESC;

